version: "3.9"
services:
  frontend:
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - "12345:80"
    networks:
      - movienet
    environment:
      - BACKEND_PORT=8080
      - PORT=80
    depends_on: 
      - backend
    restart: on-failure
    volumes:
      - ${VOLUMES_LOCATION}:/root/media
    

  backend:
    build:
      dockerfile: Dockerfile.backend
    networks:
      - movienet
    environment:
      - MOVIE_DB_POSTGRES_URL=postgresql://root:root@database:5432/kie
      - BACKEND_PORT=8080
    depends_on: 
      - database
    restart: on-failure
    volumes:
      - ${VOLUMES_LOCATION}:/root/media

  database:
    image: postgres:latest
    networks:
      - movienet
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=kie
    restart: always


networks:
  movienet:
    driver: bridge
